name: askia_farms
description: Poultry management system from Askia Farms

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_storage: ^10.2.18

  image_picker: ^0.8.5+3
  reactive_forms: ^13.0.0
  shared_preferences: ^2.0.15
  google_sign_in: ^5.3.3
  avatar_glow: ^2.0.2
  paginate_firestore: ^1.0.3+1
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  flutter_native_splash: ^2.2.4
  awesome_notifications: ^0.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.jpg"
    background_color: "#282828"
    theme_color: "#282828"
  windows:
    generate: true
    image_path: "assets/icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  color_dark: "#121212"
  image_dark: assets/splash.png

  android_12:
    image: assets/splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/splash.png
    icon_background_color_dark: "#121212"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/icon-t.png